[project]
scalaVersion = "2.13.0"
scalaNativeVersion = "0.3.9"
testFrameworks = ["minitest.runner.Framework"]

[module.example]
root = "shared"
sources = ["shared/src"]

[module.example.test]
sources = ["shared/test"]
scalaDeps = [["io.monix", "minitest", "2.6.0"]]

[module.example.jvm]
root = "jvm"
sources = ["jvm/src"]
scalaDeps = [
  ["com.github.pathikrit", "better-files", "3.8.0"]
]
javaDeps = [
  ["com.twelvemonkeys.imageio", "imageio-jpeg", "3.4.2"],
  ["com.twelvemonkeys.imageio", "imageio-core", "3.4.2"]
]

[module.example.test.jvm]
sources = ["jvm/test"]

[module.example.native]
root = "native"
scalaVersion = "2.11.12"
sources = ["native/src"]

[module.example.test.native]
sources = ["native/test"]
